spring:
  application:
    name: oro

  liquibase:
    change-log: classpath:db/changelog/changelog.xml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 900
  refreshTokenExpiration: 604800

app:
  base-url: ${APP_BASE_URL}
  cors:
    allowed-origin: ${APP_CORS_ALLOWED_ORIGIN}
  password-reset:
    expiry-minutes: 15

novu:
  api:
    key: ${NOVU_SECRET:secret}
  subscriber:
    locale: ${NOVU_SUBSCRIBER_LOCALE:en-KE}
    timezone: ${NOVU_SUBSCRIBER_TIMEZONE:Africa/Nairobi}