spring:
  application:
    name: oro

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    enabled: true

app:
  base-url: ${APP_BASE_URL}

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 900
  refreshTokenExpiration: 604800

novu:
  secret: ${NOVU_SECRET}

mpesa:
  base-url: ${MPESA_BASE_URL}
  consumer-key: ${MPESA_CONSUMER_KEY}
  consumer-secret: ${MPESA_CONSUMER_SECRET}
  shortcode: ${MPESA_SHORTCODE}
  passkey: ${MPESA_PASSKEY}
  callback-url: ${MPESA_CALLBACK_URL}
  endpoints:
    auth: ${MPESA_AUTH_ENDPOINT}
    stk-push: ${MPESA_STK_PUSH_ENDPOINT}