spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testing_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    com.oro.api: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  base-url: ${APP_BASE_URL:http://localhost:4200}

jwt:
  secret: ${JWT_SECRET:secret}
  access-token-expiration: 120
  refresh-token-expiration: 300

cookie:
  secure: false

mpesa:
  base-url: ${MPESA_BASE_URL:https://sandbox.safaricom.co.ke}
  callback-url: ${MPESA_CALLBACK_URL:https://your-ngrok-url.ngrok.io/api/mpesa/stk/callback}
  endpoints:
    auth: ${MPESA_AUTH_ENDPOINT:/oauth/v1/generate?grant_type=client_credentials}
    stk-push: ${MPESA_STK_PUSH_ENDPOINT:/mpesa/stkpush/v1/processrequest}