spring:
  datasource:
    url: jdbc:mysql://localhost:3306/puuuul?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME:puuuul-db-user}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    com.puuul.api: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  base-url: ${APP_BASE_URL:http://localhost:4200}

jwt:
  secret: ${JWT_SECRET:secret}
  access-token-expiration: 120
  refresh-token-expiration: 300

cookie:
  secure: false
server:
  port: 9096