jwt:
  access-token-expiration: 900
  refresh-token-expiration: 604800

cookie:
  secure: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
