### Merchant self-registration (public)
POST http://localhost:9096/auth/register
Content-Type: application/json

{
  "firstName": "Dickens",
  "lastName": "Onyango",
  "password": "123456789",
  "email": "omondikens1@gmail.com",
  "phoneNumber": "0707127309"
}

