POST http://localhost:8080/users
Content-Type: application/json

{
  "password": "123456789",
  "email": "omondikens1@gmail.com",
  "userName": "ken",
  "phoneNumber": "0707127309",
  "role": "CUSTOMER"
}