services:
  db:
    image: mysql:8.0.33
    container_name: testing_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing_db
    volumes:
      - 'testing-db:/var/lib/mysql'
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      retries: 10

volumes:
  testing-db: